export {
	canOpenDesktopSettingsBeforeSetup,
	type DesktopAction,
	type DesktopBridge,
	type DesktopBridgeWindow,
	type DesktopServiceStatus,
	type DesktopSettingsBridge,
	type DesktopStatus,
	type DesktopThermalSample,
	type DesktopUpdateState,
	type DesktopUpdateStatus,
	desktopErrorMessage,
	desktopSettingsBridge,
	isDesktopApp,
	readDesktopBridge,
} from "./desktopBridge.ts";
