/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GalleryRouteImport } from './routes/[_]gallery'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AllRouteRouteImport } from './routes/all/route'
import { Route as NeedsYouRouteRouteImport } from './routes/needs-you/route'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AllBoardRouteImport } from './routes/all_.board'
import { Route as PSplatRouteRouteImport } from './routes/p/$/route'
import { Route as TIdentifierRouteRouteImport } from './routes/t/$identifier/route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/_gallery',
  path: '/_gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AllRouteRoute = AllRouteRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => rootRouteImport,
} as any)
const NeedsYouRouteRoute = NeedsYouRouteRouteImport.update({
  id: '/needs-you',
  path: '/needs-you',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AllBoardRoute = AllBoardRouteImport.update({
  id: '/all_/board',
  path: '/all/board',
  getParentRoute: () => rootRouteImport,
} as any)
const PSplatRouteRoute = PSplatRouteRouteImport.update({
  id: '/p/$',
  path: '/p/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TIdentifierRouteRoute = TIdentifierRouteRouteImport.update({
  id: '/t/$identifier',
  path: '/t/$identifier',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/all': typeof AllRouteRoute
  '/needs-you': typeof NeedsYouRouteRoute
  '/_gallery': typeof GalleryRoute
  '/agents': typeof AgentsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/p/$': typeof PSplatRouteRoute
  '/t/$identifier': typeof TIdentifierRouteRoute
  '/all/board': typeof AllBoardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/all': typeof AllRouteRoute
  '/needs-you': typeof NeedsYouRouteRoute
  '/_gallery': typeof GalleryRoute
  '/agents': typeof AgentsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/p/$': typeof PSplatRouteRoute
  '/t/$identifier': typeof TIdentifierRouteRoute
  '/all/board': typeof AllBoardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/all': typeof AllRouteRoute
  '/needs-you': typeof NeedsYouRouteRoute
  '/_gallery': typeof GalleryRoute
  '/agents': typeof AgentsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/p/$': typeof PSplatRouteRoute
  '/t/$identifier': typeof TIdentifierRouteRoute
  '/all_/board': typeof AllBoardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/all'
    | '/needs-you'
    | '/_gallery'
    | '/agents'
    | '/search'
    | '/settings'
    | '/setup'
    | '/p/$'
    | '/t/$identifier'
    | '/all/board'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/all'
    | '/needs-you'
    | '/_gallery'
    | '/agents'
    | '/search'
    | '/settings'
    | '/setup'
    | '/p/$'
    | '/t/$identifier'
    | '/all/board'
  id:
    | '__root__'
    | '/'
    | '/all'
    | '/needs-you'
    | '/_gallery'
    | '/agents'
    | '/search'
    | '/settings'
    | '/setup'
    | '/p/$'
    | '/t/$identifier'
    | '/all_/board'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllRouteRoute: typeof AllRouteRoute
  NeedsYouRouteRoute: typeof NeedsYouRouteRoute
  GalleryRoute: typeof GalleryRoute
  AgentsRoute: typeof AgentsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  PSplatRouteRoute: typeof PSplatRouteRoute
  TIdentifierRouteRoute: typeof TIdentifierRouteRoute
  AllBoardRoute: typeof AllBoardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gallery': {
      id: '/_gallery'
      path: '/_gallery'
      fullPath: '/_gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all': {
      id: '/all'
      path: '/all'
      fullPath: '/all'
      preLoaderRoute: typeof AllRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/needs-you': {
      id: '/needs-you'
      path: '/needs-you'
      fullPath: '/needs-you'
      preLoaderRoute: typeof NeedsYouRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all_/board': {
      id: '/all_/board'
      path: '/all/board'
      fullPath: '/all/board'
      preLoaderRoute: typeof AllBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$': {
      id: '/p/$'
      path: '/p/$'
      fullPath: '/p/$'
      preLoaderRoute: typeof PSplatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$identifier': {
      id: '/t/$identifier'
      path: '/t/$identifier'
      fullPath: '/t/$identifier'
      preLoaderRoute: typeof TIdentifierRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllRouteRoute: AllRouteRoute,
  NeedsYouRouteRoute: NeedsYouRouteRoute,
  GalleryRoute: GalleryRoute,
  AgentsRoute: AgentsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  PSplatRouteRoute: PSplatRouteRoute,
  TIdentifierRouteRoute: TIdentifierRouteRoute,
  AllBoardRoute: AllBoardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
