/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GalleryRouteImport } from './routes/[_]gallery'
import { Route as LoopsRouteImport } from './routes/loops'
import { Route as NeedsYouRouteRouteImport } from './routes/needs-you/route'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as AiFlowsRouteImport } from './routes/ai.flows'
import { Route as PSplatRouteRouteImport } from './routes/p/$/route'
import { Route as SessionsIdRouteImport } from './routes/sessions.$id'
import { Route as TIdentifierRouteRouteImport } from './routes/t/$identifier/route'
import { Route as AiFlowsSlugRouteImport } from './routes/ai.flows_.$slug'
import { Route as SessionsProjectProjectRouteImport } from './routes/sessions.project.$project'
import { Route as ReviewsOwnerRepoNumberRouteImport } from './routes/reviews_.$owner.$repo.$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/_gallery',
  path: '/_gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LoopsRoute = LoopsRouteImport.update({
  id: '/loops',
  path: '/loops',
  getParentRoute: () => rootRouteImport,
} as any)
const NeedsYouRouteRoute = NeedsYouRouteRouteImport.update({
  id: '/needs-you',
  path: '/needs-you',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const AiFlowsRoute = AiFlowsRouteImport.update({
  id: '/ai/flows',
  path: '/ai/flows',
  getParentRoute: () => rootRouteImport,
} as any)
const PSplatRouteRoute = PSplatRouteRouteImport.update({
  id: '/p/$',
  path: '/p/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIdRoute = SessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TIdentifierRouteRoute = TIdentifierRouteRouteImport.update({
  id: '/t/$identifier',
  path: '/t/$identifier',
  getParentRoute: () => rootRouteImport,
} as any)
const AiFlowsSlugRoute = AiFlowsSlugRouteImport.update({
  id: '/ai/flows_/$slug',
  path: '/ai/flows/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsProjectProjectRoute = SessionsProjectProjectRouteImport.update({
  id: '/sessions/project/$project',
  path: '/sessions/project/$project',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsOwnerRepoNumberRoute = ReviewsOwnerRepoNumberRouteImport.update({
  id: '/reviews_/$owner/$repo/$number',
  path: '/reviews/$owner/$repo/$number',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/needs-you': typeof NeedsYouRouteRoute
  '/_gallery': typeof GalleryRoute
  '/loops': typeof LoopsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/usage': typeof UsageRoute
  '/p/$': typeof PSplatRouteRoute
  '/t/$identifier': typeof TIdentifierRouteRoute
  '/ai/flows': typeof AiFlowsRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/ai/flows/$slug': typeof AiFlowsSlugRoute
  '/sessions/project/$project': typeof SessionsProjectProjectRoute
  '/reviews/$owner/$repo/$number': typeof ReviewsOwnerRepoNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/needs-you': typeof NeedsYouRouteRoute
  '/_gallery': typeof GalleryRoute
  '/loops': typeof LoopsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/usage': typeof UsageRoute
  '/p/$': typeof PSplatRouteRoute
  '/t/$identifier': typeof TIdentifierRouteRoute
  '/ai/flows': typeof AiFlowsRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/ai/flows/$slug': typeof AiFlowsSlugRoute
  '/sessions/project/$project': typeof SessionsProjectProjectRoute
  '/reviews/$owner/$repo/$number': typeof ReviewsOwnerRepoNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/needs-you': typeof NeedsYouRouteRoute
  '/_gallery': typeof GalleryRoute
  '/loops': typeof LoopsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/usage': typeof UsageRoute
  '/p/$': typeof PSplatRouteRoute
  '/t/$identifier': typeof TIdentifierRouteRoute
  '/ai/flows': typeof AiFlowsRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/ai/flows_/$slug': typeof AiFlowsSlugRoute
  '/sessions/project/$project': typeof SessionsProjectProjectRoute
  '/reviews_/$owner/$repo/$number': typeof ReviewsOwnerRepoNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/needs-you'
    | '/_gallery'
    | '/loops'
    | '/search'
    | '/settings'
    | '/setup'
    | '/usage'
    | '/p/$'
    | '/t/$identifier'
    | '/ai/flows'
    | '/sessions/$id'
    | '/ai/flows/$slug'
    | '/sessions/project/$project'
    | '/reviews/$owner/$repo/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/needs-you'
    | '/_gallery'
    | '/loops'
    | '/search'
    | '/settings'
    | '/setup'
    | '/usage'
    | '/p/$'
    | '/t/$identifier'
    | '/ai/flows'
    | '/sessions/$id'
    | '/ai/flows/$slug'
    | '/sessions/project/$project'
    | '/reviews/$owner/$repo/$number'
  id:
    | '__root__'
    | '/'
    | '/needs-you'
    | '/_gallery'
    | '/loops'
    | '/search'
    | '/settings'
    | '/setup'
    | '/usage'
    | '/p/$'
    | '/t/$identifier'
    | '/ai/flows'
    | '/sessions/$id'
    | '/ai/flows_/$slug'
    | '/sessions/project/$project'
    | '/reviews_/$owner/$repo/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NeedsYouRouteRoute: typeof NeedsYouRouteRoute
  GalleryRoute: typeof GalleryRoute
  LoopsRoute: typeof LoopsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  UsageRoute: typeof UsageRoute
  PSplatRouteRoute: typeof PSplatRouteRoute
  TIdentifierRouteRoute: typeof TIdentifierRouteRoute
  AiFlowsRoute: typeof AiFlowsRoute
  SessionsIdRoute: typeof SessionsIdRoute
  AiFlowsSlugRoute: typeof AiFlowsSlugRoute
  SessionsProjectProjectRoute: typeof SessionsProjectProjectRoute
  ReviewsOwnerRepoNumberRoute: typeof ReviewsOwnerRepoNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gallery': {
      id: '/_gallery'
      path: '/_gallery'
      fullPath: '/_gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loops': {
      id: '/loops'
      path: '/loops'
      fullPath: '/loops'
      preLoaderRoute: typeof LoopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/needs-you': {
      id: '/needs-you'
      path: '/needs-you'
      fullPath: '/needs-you'
      preLoaderRoute: typeof NeedsYouRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/flows': {
      id: '/ai/flows'
      path: '/ai/flows'
      fullPath: '/ai/flows'
      preLoaderRoute: typeof AiFlowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$': {
      id: '/p/$'
      path: '/p/$'
      fullPath: '/p/$'
      preLoaderRoute: typeof PSplatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$id': {
      id: '/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof SessionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$identifier': {
      id: '/t/$identifier'
      path: '/t/$identifier'
      fullPath: '/t/$identifier'
      preLoaderRoute: typeof TIdentifierRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/flows_/$slug': {
      id: '/ai/flows_/$slug'
      path: '/ai/flows/$slug'
      fullPath: '/ai/flows/$slug'
      preLoaderRoute: typeof AiFlowsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/project/$project': {
      id: '/sessions/project/$project'
      path: '/sessions/project/$project'
      fullPath: '/sessions/project/$project'
      preLoaderRoute: typeof SessionsProjectProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews_/$owner/$repo/$number': {
      id: '/reviews_/$owner/$repo/$number'
      path: '/reviews/$owner/$repo/$number'
      fullPath: '/reviews/$owner/$repo/$number'
      preLoaderRoute: typeof ReviewsOwnerRepoNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NeedsYouRouteRoute: NeedsYouRouteRoute,
  GalleryRoute: GalleryRoute,
  LoopsRoute: LoopsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  UsageRoute: UsageRoute,
  PSplatRouteRoute: PSplatRouteRoute,
  TIdentifierRouteRoute: TIdentifierRouteRoute,
  AiFlowsRoute: AiFlowsRoute,
  SessionsIdRoute: SessionsIdRoute,
  AiFlowsSlugRoute: AiFlowsSlugRoute,
  SessionsProjectProjectRoute: SessionsProjectProjectRoute,
  ReviewsOwnerRepoNumberRoute: ReviewsOwnerRepoNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
