import { expect, test } from "@playwright/test";
import { ensureProject } from "./cli";
import { signIn } from "./support";

test.beforeAll(() => ensureProject("RVW", "Local reviews"));

test("reviews > a local comment persists and the review form matches GitHub", async ({ page }) => {
	const errors: string[] = [];
	page.on("pageerror", (error) => errors.push(error.message));
	await signIn(page, "/reviews/acme/web/7");
	await expect(page.locator("diffs-container")).toHaveCount(1);
	await page.getByRole("radio", { name: "Split", exact: true }).check();
	await expect(page.locator("[data-diff-type='split']")).toBeVisible();
	await page.locator("diffs-container [data-line-type='change-addition'][data-line-index]").last().click();
	const composer = page.getByRole("form", { name: "Add review comment" });
	await expect(page.getByRole("dialog")).toHaveCount(0);
	await composer.getByRole("textbox", { name: "Comment", exact: true }).fill("Keep the value within the transaction.");
	await composer.getByRole("button", { name: "Add comment" }).click();
	await expect(page.getByRole("article", { name: "Thread by dana" }).last()).toContainText("Keep the value");
	await page.reload();
	await expect(page.getByRole("article", { name: "Thread by dana" }).last()).toContainText("Keep the value");
	await page.getByRole("button", { name: "Submit review", exact: true }).click();
	const submit = page.getByRole("dialog", { name: "Review changes" });
	await expect(submit.getByRole("radio", { name: /^Comment/ })).toBeChecked();
	await expect(submit.getByRole("radio", { name: /^Approve/ })).toBeVisible();
	await expect(submit.getByRole("radio", { name: /^Request changes/ })).toBeVisible();
	await expect(submit.getByText("Notify agents")).toHaveCount(0);
	await submit.getByRole("radio", { name: /^Approve/ }).check();
	await submit.getByRole("textbox", { name: "Review summary" }).fill("The change is ready.");
	await submit.getByRole("button", { name: "Submit review" }).click();
	await expect(submit).toHaveCount(0);
	const thread = page.getByRole("article", { name: "Thread by dana" }).last();
	await thread.getByRole("textbox", { name: "Reply" }).fill("Fixed and verified.");
	await thread.getByRole("button", { name: "Post reply" }).click();
	await expect(thread.getByRole("textbox", { name: "Reply" })).toBeFocused();
	await thread.getByRole("button", { name: "Resolve thread" }).click();
	await expect(thread).toContainText("Resolved by dana");
	await page.reload();
	await expect(page.getByRole("article", { name: "Thread by dana" }).last()).toContainText("Resolved by dana");
	expect(errors).toEqual([]);
});
