import { call, os } from "./base";
export const reviews = os.reviews.router({
	status: os.reviews.status.handler(({ context, input }) => call(context, "reviews.status", input)),
	reviewers: os.reviews.reviewers.handler(({ context, input }) => call(context, "reviews.reviewers", input)),
	reviewer: os.reviews.reviewer.handler(({ context, input }) => call(context, "reviews.reviewer", input)),
	action: os.reviews.action.handler(({ context, input }) => call(context, "reviews.action", input)),
	metadata: os.reviews.metadata.handler(({ context, input }) => call(context, "reviews.metadata", input)),
	mine: os.reviews.mine.handler(({ context, input }) => call(context, "reviews.mine", input)),
	export: os.reviews.export.handler(({ context, input }) => call(context, "reviews.export", input)),
	refresh: os.reviews.refresh.handler(({ context, input }) => call(context, "reviews.refresh", input)),
	revision: os.reviews.revision.handler(({ context, input }) => call(context, "reviews.revision", input)),
	file: os.reviews.file.handler(({ context, input }) => call(context, "reviews.file", input)),

	open: os.reviews.open.handler(({ context, input }) => call(context, "reviews.open", input)),
	prs: os.reviews.prs.handler(({ context, input }) => call(context, "reviews.prs", input)),
	list: os.reviews.list.handler(({ context, input }) => call(context, "reviews.list", input)),
	thread: os.reviews.thread.handler(({ context, input }) => call(context, "reviews.thread", input)),
	add: os.reviews.add.handler(({ context, input }) => call(context, "reviews.add", input)),
	reply: os.reviews.reply.handler(({ context, input }) => call(context, "reviews.reply", input)),
	resolve: os.reviews.resolve.handler(({ context, input }) => call(context, "reviews.resolve", input)),
	edit: os.reviews.edit.handler(({ context, input }) => call(context, "reviews.edit", input)),
	reaction: os.reviews.reaction.handler(({ context, input }) => call(context, "reviews.reaction", input)),
	submit: os.reviews.submit.handler(({ context, input }) => call(context, "reviews.submit", input)),
	apply: os.reviews.apply.handler(({ context, input }) => call(context, "reviews.apply", input)),
});
