import { afterEach, expect, test } from "bun:test";
import { readDocumentRevision, readDocumentSaveReceipt } from "../../../db/queries/langflowDocuments";
import { documentBytes } from "../documentBytes";
import { flowId } from "../fixture";
import { get } from "../get";
import { legacyServices } from "../legacyServices";
import { editFixture } from "./fixture";
import { saveConversionEdit } from "./saveConversionEdit";

let f: Awaited<ReturnType<typeof editFixture>>;
afterEach(async () => {
	await f?.db.$client.close();
});

test("commits generated bytes, metadata, and original intent receipt together", async () => {
	f = await editFixture();
	const result = await saveConversionEdit(f.io, f.intent, f.services);
	if (!("document" in result)) throw new Error("fixture_blocked");
	expect(result.document.flow.briefing).toBe("  Retained\nbriefing.  ");
	expect(result.document.revision).toBe(f.base.revision + 1);
	const receipt = await f.run((tx) => readDocumentSaveReceipt(tx, f.intent));
	expect(receipt!.requestBytes).toEqual(documentBytes(f.intent));
	expect(receipt!.receipt).toEqual(result.document);
	const prior = await f.run((tx) => readDocumentRevision(tx, { flowId, revision: f.base.revision }));
	expect(prior!.snapshot.flow.briefing).toBe(f.base.flow.briefing);
	const saved = await f.run((tx) => readDocumentRevision(tx, { flowId, revision: result.document.revision }));
	expect(saved!.snapshot.graphDocument).toEqual(result.document.graphDocument);
});

test("replays an original response after a rename without producer access", async () => {
	f = await editFixture();
	const original = await saveConversionEdit(f.io, f.intent, f.services);
	await f.run((tx) => legacyServices.update(f.ctx, tx, { flow: flowId, expectedVersion: 2, name: "Later name" }));
	const unavailable = () => {
		throw new Error("producer_unavailable");
	};
	expect(await saveConversionEdit(f.io, f.intent, { prepare: unavailable, installedIdentity: unavailable })).toEqual(
		original,
	);
	await expect(
		saveConversionEdit(f.io, { ...f.intent, edits: [{ kind: "set-flow-briefing", briefing: "Changed" }] }, f.services),
	).rejects.toMatchObject({ code: "FLOW_REQUEST_CONFLICT" });
});

test("a blocked producer writes no receipt or changed metadata", async () => {
	f = await editFixture();
	const result = await saveConversionEdit(f.io, f.intent, {
		...f.services,
		prepare: async () => ({
			state: "blocked",
			diagnostics: [{ code: "producer_unavailable", message: "Unavailable", severity: "error", path: [] }],
		}),
	});
	expect(result).toMatchObject({ state: "blocked" });
	expect(await f.run((tx) => readDocumentSaveReceipt(tx, f.intent))).toBeUndefined();
	expect(await f.run((tx) => get(f.ctx, tx, { flow: flowId }))).toEqual(f.base);
});

test("a competing edit wins the shared version while preparation waits", async () => {
	f = await editFixture();
	const entered = Promise.withResolvers<void>();
	const release = Promise.withResolvers<void>();
	const first = saveConversionEdit(f.io, f.intent, {
		...f.services,
		prepare: async (input) => {
			entered.resolve();
			await release.promise;
			return f.services.prepare(input);
		},
	});
	const observed = first.then(
		(value) => ({ status: "fulfilled" as const, value }),
		(reason: unknown) => ({ status: "rejected" as const, reason }),
	);
	try {
		await Promise.race([
			entered.promise,
			observed.then(() => {
				throw new Error("first_edit_settled_before_release");
			}),
		]);
		const second = await saveConversionEdit(
			f.io,
			{ ...f.intent, requestId: crypto.randomUUID(), edits: [{ kind: "set-flow-briefing", briefing: "Winner" }] },
			f.services,
		);
		release.resolve();
		expect(await observed).toMatchObject({ status: "rejected", reason: { code: "FLOW_VERSION_CONFLICT" } });
		expect(second).toMatchObject({ document: { flow: { briefing: "Winner" } } });
		expect(await f.run((tx) => readDocumentSaveReceipt(tx, f.intent))).toBeUndefined();
	} finally {
		release.resolve();
		await observed;
	}
});

test.each([false, true])("a concurrent identical request returns the first receipt (blocked=%s)", async (blocked) => {
	f = await editFixture();
	const entered = Promise.withResolvers<void>();
	const release = Promise.withResolvers<void>();
	const first = saveConversionEdit(f.io, f.intent, {
		...f.services,
		prepare: async (input) => {
			entered.resolve();
			await release.promise;
			if (blocked) return { state: "blocked", diagnostics: [] };
			return f.services.prepare(input);
		},
	});
	await entered.promise;
	const second = await saveConversionEdit(f.io, f.intent, f.services);
	release.resolve();
	expect(await first).toEqual(second);
});

test("a changed installed package prevents commit after preparation", async () => {
	f = await editFixture();
	let changed = false;
	await expect(
		saveConversionEdit(f.io, f.intent, {
			prepare: async (input) => {
				const result = await f.services.prepare(input);
				changed = true;
				return result;
			},
			installedIdentity: () => ({
				...f.services.installedIdentity(),
				...(changed ? { enginePackageDigest: "f".repeat(64) } : {}),
			}),
		}),
	).rejects.toMatchObject({ code: "INPUT_VALIDATION_FAILED" });
	expect(await f.run((tx) => get(f.ctx, tx, { flow: flowId }))).toEqual(f.base);
});

test("changed prepared intent bytes cannot authorize a save", async () => {
	f = await editFixture();
	await expect(
		saveConversionEdit(f.io, f.intent, {
			...f.services,
			prepare: async (input) => {
				const result = await f.services.prepare(input);
				if (result.state !== "prepared") throw new Error("fixture_blocked");
				return { ...result, intentBytes: Buffer.from("{}") };
			},
		}),
	).rejects.toThrow("conversion_edit_preparation_conflict");
	expect(await f.run((tx) => readDocumentSaveReceipt(tx, f.intent))).toBeUndefined();
	expect(await f.run((tx) => get(f.ctx, tx, { flow: flowId }))).toEqual(f.base);
});
