import { HarnessSchema } from "../harness/harness.ts";
import type { SessionDetail } from "../schemas/session.ts";
export const at = "2026-09-18T12:00:00.000Z";
export const session = (): SessionDetail => ({
	id: "session",
	name: "test",
	projectId: null,
	projectPath: "",
	directory: "/tmp",
	harness: HarnessSchema.parse({ preset: "codex" }),
	runId: "run",
	createdAt: at,
	updatedAt: at,
	run: {
		id: "run",
		name: "test",
		runtime: "native",
		kind: "session",
		harness: HarnessSchema.parse({ preset: "codex" }),
		instruction: "",
		projectId: null,
		projectPath: "",
		ticketId: null,
		ticketIdentifier: null,
		ticketTitle: null,
		ticketStatusCategory: null,
		assigned: true,
		state: "running",
		processStatus: "running",
		workspaceId: "/tmp",
		terminalId: "attempt",
		url: null,
		error: null,
		sessionId: "conversation",
		sessionLost: false,
		createdAt: at,
		updatedAt: at,
		observation: {
			checkedAt: at,
			controllable: true,
			activity: { state: "working", updatedAt: at },
			outcome: null,
			turnId: "turn",
			attention: { sequence: 1, requests: [], completion: null, failure: null },
		},
	},
});
