export type LimitCase = { table: string; column: string; value: unknown; invalid: unknown[]; where?: string };

export const cases: LimitCase[] = [
	{
		table: "actors",
		column: "name",
		value: "a".repeat(65),
		invalid: ["", "bad:name", "bad\nname"],
		where: "name <> 'fixture'",
	},
	{ table: "tickets", column: "title", value: "t".repeat(501), invalid: ["", " padded "] },
	{ table: "projects", column: "name", value: "p".repeat(121), invalid: [""] },
	{ table: "statuses", column: "name", value: "s".repeat(41), invalid: [""] },
	{ table: "statuses", column: "description", value: "s".repeat(2001), invalid: [] },
	{ table: "epics", column: "name", value: "e".repeat(121), invalid: ["", " padded "] },
	{ table: "epics", column: "description", value: "界".repeat(200001), invalid: [] },
	{ table: "waves", column: "name", value: "w".repeat(121), invalid: ["", " padded "] },
	{ table: "sessions", column: "name", value: "界".repeat(61), invalid: ["", " padded "] },
	{ table: "attachments", column: "filename", value: "f".repeat(256), invalid: ["", "bad/file"] },
	{ table: "pages", column: "title", value: "p".repeat(201), invalid: ["", " padded "] },
	{ table: "pages", column: "summary", value: "p".repeat(2001), invalid: [] },
	{ table: "page_versions", column: "label", value: "v".repeat(201), invalid: [""] },
	{
		table: "page_versions",
		column: "source_path",
		value: "p".repeat(4097),
		invalid: ["", "/absolute", "../parent", "C:/drive", "a\\b", "a//b", "trailing/", "a\nb"],
	},
	{ table: "page_assets", column: "mime", value: "m".repeat(256), invalid: ["", "bad\nmime"] },
	{ table: "page_uploads", column: "mime", value: "m".repeat(256), invalid: ["", "bad\nmime"] },
	{ table: "page_uploads", column: "original_name", value: "f".repeat(256), invalid: ["", "a/b", "a\\b", "a\nb"] },
	{ table: "epic_resources", column: "name", value: "r".repeat(256), invalid: [" padded "], where: "id='doc'" },
	{ table: "epic_resources", column: "body", value: "界".repeat(200001), invalid: [], where: "id='doc'" },
	{
		table: "epic_resources",
		column: "url",
		value: `https://example.test/${"u".repeat(10001)}`,
		invalid: [""],
		where: "id='link'",
	},
	{ table: "resource_comments", column: "body", value: "c".repeat(10001), invalid: [""] },
	{ table: "resource_comments", column: "quote", value: "q".repeat(2001), invalid: [""] },
	{ table: "notes", column: "body", value: "n".repeat(4001), invalid: [""] },
	{ table: "page_comments", column: "body", value: "c".repeat(10001), invalid: [""] },
	{ table: "page_comment_threads", column: "selected_text", value: "s".repeat(2001), invalid: ["", null] },
	{
		table: "page_comment_threads",
		column: "anchor",
		value: { kind: "text", content: "a".repeat(16385) },
		invalid: [{}, { kind: "element" }, []],
	},
	{ table: "providers", column: "name", value: "p".repeat(121), invalid: ["", " padded "] },
	{ table: "providers", column: "base_url", value: "u".repeat(2001), invalid: [""] },
	{ table: "providers", column: "api_key", value: "k".repeat(4001), invalid: [""] },
	{ table: "provider_models", column: "model_id", value: "m".repeat(201), invalid: ["", "space here", "a\nb"] },
	{
		table: "label_groups",
		column: "name",
		value: "g".repeat(81),
		invalid: ["", " padded ", "none", "None", "a/b", "a,b"],
	},
	{
		table: "labels",
		column: "name",
		value: "l".repeat(81),
		invalid: ["", " padded ", "none", "a/b", "a,b"],
		where: "id='label'",
	},
	{ table: "labels", column: "description", value: "d".repeat(256), invalid: [] },
];
