import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

// Writes src/theme/tokens.ts from packages/ui/src/tokens.css. React Native
// cannot read a CSS custom property, so the same values become one TypeScript
// object. The CSS file is the source and the output is never edited by hand.
// The first argument names another output path, which the sync test uses.
const source = join(import.meta.dir, "../../../packages/ui/src/tokens.css");
const target = process.argv[2] ?? join(import.meta.dir, "../src/theme/tokens.ts");

const css = readFileSync(source, "utf8");

// The `--name: value;` declarations of the block that opens with `prelude {`.
// The palette blocks hold no nested block, so the first `}` closes them.
const declarations = (prelude: string): Record<string, string> => {
	const start = css.indexOf(`${prelude} {`);
	const end = css.indexOf("}", start);
	const body = css.slice(start + prelude.length + 2, end);
	return Object.fromEntries(
		[...body.matchAll(/--([\w-]+):\s*([^;]+);/g)].map((match) => [match[1]!, match[2]!.trim()]),
	);
};

// A px value from a `--prefix-name: <n>px;` declaration anywhere in the file,
// as a map of name to number. `name` stops at a colon, so `--text-xs` and
// `--text-xs--line-height` land in two different maps.
const pxScale = (prefix: string, suffix = ""): Record<string, number> =>
	Object.fromEntries(
		[...css.matchAll(new RegExp(`--${prefix}-([a-z0-9]+)${suffix}:\\s*(\\d+)px;`, "g"))].map((match) => [
			match[1]!,
			Number(match[2]),
		]),
	);

const camel = (name: string) => name.replace(/-([a-z])/g, (_, letter: string) => letter.toUpperCase());

// The color tokens are every custom property of the light block except the
// shadows, the text-on-fill color, and the two font stacks.
const isColor = (name: string) => !name.startsWith("shadow-") && !["on-accent", "sans", "mono"].includes(name);

const light = declarations(":root");
const dark = declarations(':root[data-theme="dark"]');
const colorNames = Object.keys(light).filter(isColor);

// BerkeleyMono is licensed per machine, so the repo ships no file for it. It
// leads the CSS stacks because a desktop browser picks up a font the machine
// has installed. React Native draws only a family it holds a file for, and
// app/_layout.tsx loads JetBrains Mono under the name below.
const licensedPerMachine = "BerkeleyMono";

// The first family of a CSS font stack that this repo ships a file for,
// without the " Variable" suffix of a variable font. expo-font registers the
// family under that name.
const family = (stack: string) =>
	[...stack.matchAll(/"([^"]+)"/g)]
		.map((match) => match[1]!.replace(/ Variable$/, ""))
		.find((name) => name !== licensedPerMachine)!;

// The seven steps of the type scale. The other `--text-*` sizes are the micro
// steps a Kbd and a human Avatar use.
const scaleSteps = ["xs", "sm", "base", "md", "lg", "xl", "2xl"];
const sizes = pxScale("text");
const leadings = pxScale("text", "--line-height");
const radii = pxScale("radius");
const spacingBase = Number(/--spacing:\s*(\d+)px;/.exec(css)![1]);

const pick = (map: Record<string, number>, names: string[]) =>
	Object.fromEntries(names.map((name) => [name, map[name]!]));
const omit = (map: Record<string, number>, names: string[]) =>
	Object.fromEntries(Object.entries(map).filter(([name]) => !names.includes(name)));

const palette = (values: Record<string, string>) =>
	colorNames.map((name) => `\t\t${camel(name)}: "${values[name]!}",`).join("\n");

const numbers = (map: Record<string, number>) =>
	Object.entries(map)
		.map(([name, value]) => `${/^\d/.test(name) ? `"${name}"` : name}: ${value}`)
		.join(", ");

// The spacing scale is the Tailwind multiples of the 4 px base.
const space = Object.fromEntries([1, 2, 3, 4, 5, 6, 8, 10, 12].map((step) => [String(step), step * spacingBase]));

const output = `// Generated by scripts/generate-tokens.ts from packages/ui/src/tokens.css.
// Do not edit. Run \`bun run generate:tokens\` after a change to the CSS.

export const tokens = {
	light: {
${palette(light)}
	},
	dark: {
${palette(dark)}
	},
	// Text on a saturated fill (accent, danger) stays white in both themes.
	onAccent: "${light["on-accent"]!}",
	font: { sans: "${family(light.sans!)}", mono: "${family(light.mono!)}" },
	text: { ${numbers(pick(sizes, scaleSteps))} },
	leading: { ${numbers(pick(leadings, scaleSteps))} },
	micro: { ${numbers(omit(sizes, scaleSteps))} },
	// Half of the 4 px base, for a 2 px gap.
	space: { half: ${spacingBase / 2}, ${numbers(space)} },
	radius: { ${numbers(omit(radii, ["hairline"]))} },
	hairline: ${radii.hairline!},
};

export type ColorToken = keyof typeof tokens.light;
export type Palette = Record<ColorToken, string>;
`;

writeFileSync(target, output);
