import {
	AgentRunSchema,
	EpicSchema,
	HarnessAccountSchema,
	HarnessSchema,
	LabelSchema,
	PageDetailSchema,
	ProjectSchema,
	SessionSchema,
	StatusSchema,
	TicketSchema,
	WaveSummarySchema,
} from "@trellis/api";

export const at = "2026-09-30T12:00:00.000Z";
export const id = (number: number) => `01M0000000000000000000${String(number).padStart(4, "0")}`;
export const actor = { name: "avery", displayName: "Avery", kind: "human" as const };
export const counts = { total: 4, todo: 2, started: 1, review: 0, done: 1, canceled: 0 };
export const statuses = [
	["todo", "Todo", "todo", "fg-muted"],
	["in-progress", "In progress", "started", "warning"],
	["review", "Review", "review", "accent"],
	["done", "Done", "done", "success"],
	["canceled", "Canceled", "canceled", "fg-muted"],
].map(([slug, name, category, color], index) =>
	StatusSchema.parse({
		id: id(10 + index),
		projectId: id(1),
		slug,
		name,
		category,
		color,
		description: "The status identifies the current work stage.",
		position: index,
		isDefault: index === 0,
		createdAt: at,
		updatedAt: at,
	}),
);
export const project = ProjectSchema.parse({
	id: id(1),
	key: "DEMO",
	slug: "demo",
	name: "Demo project",
	position: 0,
	openCount: 3,
	openEpicCount: 1,
	openPageCommentCount: 0,
	color: "blue",
	archivedAt: null,
	directory: "/workspace/demo",
	description: "Local Storybook fixtures.",
	ticketTemplate: "",
	ticketCounter: 4,
	createdAt: at,
	updatedAt: at,
	repos: [],
	statuses,
});
export const projects = [project, { ...project, id: id(2), key: "LAB", slug: "lab", name: "Lab", position: 1 }];
export const wave = WaveSummarySchema.parse({
	id: id(20),
	epicId: id(3),
	ref: "DEMO/catalog/first-wave",
	slug: "first-wave",
	name: "First wave",
	position: 0,
	counts,
	state: "open",
	toStart: 2,
	waitsForYou: 0,
	createdAt: at,
	updatedAt: at,
});
export const ticket = TicketSchema.parse({
	id: id(30),
	identifier: "DEMO-1",
	number: 1,
	title: "Build the component catalog",
	priority: "high",
	status: statuses[0],
	project: { id: project.id, key: project.key },
	parent: null,
	ancestors: [],
	epic: { id: id(3), ref: "DEMO/catalog", name: "Component catalog" },
	wave,
	childCount: 0,
	childDoneCount: 0,
	attachmentCount: 0,
	labels: [],
	waitsOn: [],
	releases: [],
	ready: true,
	pr: null,
	prRows: [],
	lastActor: { ...actor, at },
	position: 0,
	version: 1,
	createdAt: at,
	updatedAt: at,
	completedAt: null,
	description: "Make every control easy to inspect.",
	outcome: "",
	children: [],
	prs: [],
	attachments: [],
	contract: { result: "", files: [], leaveAlone: [], verify: [], reviewFocus: [] },
});
export const tickets = [
	ticket,
	{ ...ticket, id: id(31), identifier: "DEMO-2", number: 2, title: "Review the catalog" },
];
export const epic = EpicSchema.parse({
	id: id(3),
	projectId: project.id,
	projectKey: project.key,
	ref: "DEMO/catalog",
	slug: "catalog",
	name: "Component catalog",
	description: "Inspect controls with local fixtures.",
	counts,
	state: "open",
	currentWave: wave,
	currentWaveIndex: 1,
	waveCount: 1,
	resourceCount: 0,
	actor,
	createdAt: at,
	updatedAt: at,
	waves: [wave],
	tickets,
});
export const labels = ["Design", "Bug", "Documentation"].map((name, index) =>
	LabelSchema.parse({
		id: id(40 + index),
		projectId: project.id,
		groupId: null,
		name,
		color: ["blue", "red", "green"][index],
		description: `${name} work.`,
		ticketCount: index + 1,
		createdAt: at,
		updatedAt: at,
	}),
);
export const harness = HarnessSchema.parse({ preset: "claude" });
export const accounts = ["Primary", "Team"].map((name, index) =>
	HarnessAccountSchema.parse({
		id: id(50 + index),
		name,
		harness: "claude",
		profilePath: `/profiles/${name.toLowerCase()}`,
		isDefault: index === 0,
		loginCommand: null,
		capabilities: { launch: true, resumeWithAccount: true, quota: true, detail: null },
		createdAt: at,
		updatedAt: at,
	}),
);
export const run = AgentRunSchema.parse({
	id: id(60),
	name: "Catalog agent",
	accountId: accounts[0]!.id,
	runtime: "native",
	harness,
	kind: "session",
	projectId: null,
	projectKey: "",
	ticketId: null,
	ticketIdentifier: null,
	ticketTitle: null,
	ticketStatusCategory: null,
	pinnedAt: null,
	assigned: true,
	state: "running",
	processStatus: "running",
	observation: null,
	workspaceId: "storybook-workspace",
	terminalId: "storybook-terminal",
	url: null,
	error: null,
	sessionId: "storybook-conversation",
	sessionLost: false,
	activityAt: at,
	createdAt: at,
	updatedAt: at,
});
export const session = SessionSchema.parse({
	id: id(61),
	name: "Catalog session",
	projectId: null,
	projectKey: "",
	directory: "/workspace/catalog",
	harness,
	runId: run.id,
	pinnedAt: null,
	archivedAt: null,
	createdAt: at,
	updatedAt: at,
});
export const quota = {
	accountId: accounts[0]!.id,
	status: "ok",
	email: "avery@example.test",
	plan: "Team",
	detail: null,
	windows: [{ id: "five_hour", label: "Five hours", usedPercent: 28, resetsAt: at }],
	creditsBalance: null,
	extraUsage: null,
	fetchedAt: at,
};
export const page = PageDetailSchema.parse({
	id: id(70),
	projectId: project.id,
	projectKey: project.key,
	ref: "DEMO/pages/catalog",
	slug: "catalog",
	title: "Component catalog",
	summary: "The local catalog of controls.",
	revision: 1,
	latestVersion: 1,
	creator: actor,
	actor,
	publishedBy: actor,
	publishedAt: at,
	watcher: null,
	pinned: false,
	openThreadCount: 0,
	deletedAt: null,
	deletedBy: null,
	purgeAt: null,
	createdAt: at,
	updatedAt: at,
	assetCount: 0,
	totalThreadCount: 0,
	resolvedThreadCount: 0,
	requestedVersion: {
		pageId: id(70),
		number: 1,
		requestId: "00000000-0000-4000-8000-000000000001",
		label: "Initial catalog",
		documentSha256: "a".repeat(64),
		documentSize: 2048,
		sourceAgentId: null,
		sourcePath: "catalog.html",
		actor,
		createdAt: at,
	},
});
export const responses = {
	"projects.list": (input: { archived?: boolean }) => (input.archived ? [] : projects),
	"projects.get": project,
	"statuses.list": { statuses },
	"epics.list": [epic],
	"epics.get": epic,
	"labels.list": { labels, groups: [] },
	"harnessAccounts.list": accounts,
	"harnessAccounts.quota": quota,
	"agentRuns.list": { items: [run], nextCursor: null },
	"sessions.list": [session],
	"actors.list": [actor],
	"search.query": { tickets, pages: [], projects, epics: [epic] },
};
export const pending = () => new Promise<never>(() => {});
export const failure = () => {
	throw new Error("The local fixture refuses this request.");
};
export const noop = () => {};
