// The names an agent can take, one word of ASCII letters each, from many
// cultures. A person says the name out loud to name one agent, so a name
// stays short and easy to say. A stored session keeps the name it took, so
// add a name here and never remove one.
export const AGENT_PERSON_NAMES: readonly string[] = [
	"Aarav",
	"Abebe",
	"Adaeze",
	"Aditi",
	"Adwoa",
	"Aiko",
	"Ainara",
	"Aisha",
	"Akira",
	"Alina",
	"Amani",
	"Amara",
	"Anahit",
	"Andile",
	"Anika",
	"Aoife",
	"Arash",
	"Arnav",
	"Asel",
	"Asma",
	"Astrid",
	"Ayaka",
	"Ayanda",
	"Balint",
	"Beatriz",
	"Bilal",
	"Birgit",
	"Bjorn",
	"Budi",
	"Bunmi",
	"Camila",
	"Ceren",
	"Chiara",
	"Chidi",
	"Cian",
	"Citlali",
	"Dalia",
	"Danilo",
	"Darya",
	"Dawit",
	"Dilnoza",
	"Diya",
	"Duc",
	"Dunja",
	"Ebele",
	"Eero",
	"Efua",
	"Eitan",
	"Elif",
	"Emeka",
	"Enkhtuya",
	"Enzo",
	"Esi",
	"Eyob",
	"Fadwa",
	"Farid",
	"Fatou",
	"Federica",
	"Feliks",
	"Freyja",
	"Fumiko",
	"Gabor",
	"Giulia",
	"Gulnara",
	"Gunnar",
	"Gwen",
	"Hana",
	"Haruto",
	"Hasan",
	"Hemi",
	"Hoang",
	"Huda",
	"Ibrahim",
	"Idris",
	"Imani",
	"Imre",
	"Ines",
	"Ingrid",
	"Isamu",
	"Itzel",
	"Ivo",
	"Jaan",
	"Jelena",
	"Joaquin",
	"Jomo",
	"Juhani",
	"Junko",
	"Jyoti",
	"Kaveh",
	"Keiko",
	"Kenji",
	"Kerem",
	"Khadija",
	"Kiran",
	"Kofi",
	"Kwame",
	"Kyaw",
	"Laila",
	"Leilani",
	"Liang",
	"Linnea",
	"Lorenzo",
	"Luana",
	"Maeve",
	"Magnus",
	"Mahdi",
	"Malak",
	"Mariam",
	"Marisol",
	"Mateo",
	"Meera",
	"Mehmet",
	"Mihaela",
	"Moana",
	"Mwangi",
	"Nadia",
	"Naledi",
	"Naoko",
	"Narek",
	"Nikoloz",
	"Nilufar",
	"Njeri",
	"Noa",
	"Nomvula",
	"Oksana",
	"Olamide",
	"Omar",
	"Ondrej",
	"Onyeka",
	"Orla",
	"Osei",
	"Padma",
	"Paloma",
	"Petra",
	"Phuong",
	"Priya",
	"Qing",
	"Quyen",
	"Rafiq",
	"Rania",
	"Ravi",
	"Reza",
	"Rhian",
	"Rustam",
	"Sakura",
	"Salma",
	"Samira",
	"Saoirse",
	"Senait",
	"Shirin",
	"Sipho",
	"Solveig",
	"Sonam",
	"Soraya",
	"Tahira",
	"Takeshi",
	"Tamar",
	"Tane",
	"Tariq",
	"Tenzin",
	"Thandiwe",
	"Thiago",
	"Tunde",
	"Uche",
	"Uma",
	"Ursula",
	"Valentina",
	"Varun",
	"Veera",
	"Vikram",
	"Vinh",
	"Wanjiru",
	"Wei",
	"Wiremu",
	"Ximena",
	"Xiulan",
	"Xochitl",
	"Yaa",
	"Yael",
	"Yara",
	"Yerlan",
	"Yohannes",
	"Yuki",
	"Yusuf",
	"Zahra",
	"Zeynep",
	"Zofia",
	"Zola",
	"Zuri",
];

// The longest name a session can store. The schema and the name column of
// agent_sessions hold each other to this number.
export const AGENT_PERSON_NAME_MAX = 40;

// One name for a new agent. `taken` holds the names of the agents that a
// person can call by name now, and the answer is none of them. `random`
// picks where in the pool the search starts, so two agents that start one
// after the other do not always get the same two names. When `taken` holds
// every name of the pool, the search walks the pool again and adds a
// number, as in "Kenji 2", so it always answers with a free name.
export const pickAgentPersonName = (taken: readonly string[], random: () => number = Math.random): string => {
	const pool = AGENT_PERSON_NAMES;
	const start = Math.floor(random() * pool.length);
	const used = new Set(taken);
	for (let round = 1; ; round += 1) {
		for (let step = 0; step < pool.length; step += 1) {
			const base = pool[(start + step) % pool.length]!;
			const name = round === 1 ? base : `${base} ${round}`;
			if (!used.has(name)) return name;
		}
	}
};
