// Generated by scripts/generate-tokens.ts from packages/ui/src/tokens.css.
// Do not edit. Run `bun run generate:tokens` after a change to the CSS.

export const tokens = {
	light: {
		bg: "#F5F5F5",
		surface: "#FFFFFF",
		elevated: "#FFFFFF",
		border: "#E5E5E5",
		borderStrong: "#D4D4D4",
		fg: "#0A0A0A",
		fgMuted: "#737373",
		fgFaint: "#A3A3A3",
		accent: "#009FFF",
		accentSoft: "#DFEBFF",
		agent: "#693ACF",
		agentSoft: "#EFE8FB",
		success: "#0DBE4E",
		successSoft: "#E3F8EA",
		warning: "#D5A910",
		warningSoft: "#FBF4DA",
		danger: "#FF2E3F",
		dangerSoft: "#FFE6E8",
		scrim: "rgba(0,0,0,.4)",
	},
	dark: {
		bg: "#0A0A0A",
		surface: "#111111",
		elevated: "#171717",
		border: "#1F1F1F",
		borderStrong: "#2A2A2A",
		fg: "#FAFAFA",
		fgMuted: "#A3A3A3",
		fgFaint: "#737373",
		accent: "#009FFF",
		accentSoft: "#19283C",
		agent: "#9D6AFB",
		agentSoft: "#24183F",
		success: "#5ECC71",
		successSoft: "#10301A",
		warning: "#FFD452",
		warningSoft: "#332B0C",
		danger: "#FF6762",
		dangerSoft: "#3A1517",
		scrim: "rgba(0,0,0,.6)",
	},
	// Text on a saturated fill (accent, danger) stays white in both themes.
	onAccent: "#FFFFFF",
	font: { sans: "Inter", mono: "JetBrains Mono" },
	text: { xs: 11, sm: 12, base: 13, md: 14, lg: 16, xl: 20, "2xl": 24 },
	leading: { xs: 16, sm: 16, base: 20, md: 22, lg: 24, xl: 28, "2xl": 32 },
	micro: { kbd: 10, initials: 9 },
	// Half of the 4 px base, for a 2 px gap.
	space: { half: 2, "1": 4, "2": 8, "3": 12, "4": 16, "5": 20, "6": 24, "8": 32, "10": 40, "12": 48 },
	radius: { sm: 0, md: 0, lg: 0, xl: 0, hairline: 0 },
	hairline: 1,
};

export type ColorToken = keyof typeof tokens.light;
export type Palette = Record<ColorToken, string>;
