import type { FlowExecutionRecord } from "@trellis/api";
import { flowV1FixtureIds as ids, legacyDocumentV1Example } from "@trellis/api";

export const fixture = (): FlowExecutionRecord => ({
	id: ids.execution,
	flowId: ids.flow,
	ticketId: ids.ticket,
	projectId: ids.project,
	diffId: null,
	repeatOf: null,
	repeatReason: null,
	revision: 12,
	headSha: "reviewed-head",
	createdAt: "2026-09-21T00:00:00.000Z",
	updatedAt: "2026-09-21T00:01:00.000Z",
	doc: {
		flow: { ...legacyDocumentV1Example.flow },
		nodes: [
			{
				id: ids.node,
				parentId: null,
				kind: "human",
				title: "Approve",
				instruction: "Read the output.",
				parallel: false,
				minutes: null,
				maxRounds: null,
				x: 0,
				y: 0,
				width: null,
				height: null,
				harness: null,
				reviewArea: null,
			},
		],
		edges: [],
	},
	state: {
		version: 1,
		flowId: ids.flow,
		flowVersion: 2,
		status: "failed",
		startedAt: Date.parse("2026-09-21T00:00:00.000Z"),
		updatedAt: Date.parse("2026-09-21T00:01:00.000Z"),
		error: "Rejected",
		steps: [
			{
				key: `root/1/${ids.node}`,
				actionKey: `root/1/${ids.node}:step:1`,
				nodeId: ids.node,
				parentKey: null,
				iteration: 1,
				round: 1,
				phase: "step",
				state: "failed",
				output: "  Exact output\n\n日本語\r\n",
				decision: null,
				error: "Rejected",
				startedAt: null,
				endedAt: null,
				deadlineAt: null,
				needsStop: false,
			},
		],
	},
	tasks: [],
});
