export const actorRelationshipMapping = [
	{ table: "activity", id: "actor_id", name: "actor_name", kind: "actor_kind", required: true },
	{ table: "attachments", id: "actor_id", name: "actor_name", kind: "actor_kind", required: true },
	{ table: "comments", id: "actor_id", name: "actor_name", kind: "actor_kind", required: true },
	{ table: "ticket_pull_requests", id: "actor_id", name: "actor_name", kind: "actor_kind", required: true },
	{ table: "epic_resources", id: "actor_id", name: "actor_name", kind: "actor_kind", required: true },
	{ table: "epics", id: "actor_id", name: "actor_name", kind: "actor_kind", required: true },
	{ table: "page_comment_threads", id: "actor_id", name: "actor_name", kind: "actor_kind", required: true },
	{
		table: "page_comment_threads",
		id: "resolved_by_id",
		name: "resolved_by_name",
		kind: "resolved_by_kind",
		required: false,
	},
	{ table: "page_comments", id: "actor_id", name: "actor_name", kind: "actor_kind", required: true },
	{ table: "page_pins", id: "actor_id", name: "actor_name", kind: "actor_kind", required: true },
	{ table: "pages", id: "creator_actor_id", name: "creator_actor_name", kind: "creator_actor_kind", required: true },
	{ table: "pages", id: "actor_id", name: "actor_name", kind: "actor_kind", required: true },
	{ table: "pages", id: "deleted_actor_id", name: "deleted_actor_name", kind: "deleted_actor_kind", required: false },
	{ table: "page_uploads", id: "actor_id", name: "actor_name", kind: "actor_kind", required: true },
	{ table: "page_versions", id: "actor_id", name: "actor_name", kind: "actor_kind", required: true },
	{ table: "pr_evidence", id: "actor_id", name: "actor_name", kind: "actor_kind", required: true },
	{ table: "pr_evidence_documents", id: "actor_id", name: "actor_name", kind: "actor_kind", required: true },
	{ table: "pr_files", id: "actor_id", name: "actor_name", kind: "actor_kind", required: true },
	{ table: "pr_flow_waivers", id: "actor_id", name: "actor_name", kind: "actor_kind", required: true },
	{ table: "resource_comments", id: "actor_id", name: "actor_name", kind: "actor_kind", required: true },
	{
		table: "resource_comments",
		id: "resolved_by_id",
		name: "resolved_by_name",
		kind: "resolved_by_kind",
		required: false,
	},
	{ table: "notes", id: "actor_id", name: "actor_name", kind: "actor_kind", required: true },
] as const;
